### PR TITLE
tutors-course-reader: eslint config & errors

### PR DESCRIPTION
**Pull request by zenby**
- Added eslint config to highlight errors
- Added scripts to run this check
- Fixed the errors as many as possible. Some of the rules in eslint config were disabled. But I'm a bit worried if i might have done some crucial changes that might break the project. Tried to run it, but i don't have .env variables, so i don't know if it works as expected. If you see any issues related to this, i can leave only eslint config related files in that PR, and get rid of other changes.
```
npm run lint
> tutors-course-reader@6.0.4 lint
> eslint ./src/**/*.{ts,svelte}  // no errors here
```
- However there are some errors left, which are highlighted by vscode pluging

image
Related issue https://github.com/sveltejs/language-tools/issues/785
Don't know what to do here.

- The same issues we can find when run `npm run check`. There are 14 errors left, but I don't know how to fix it at the moment. (However, when i started working there were more issues)

Anyway it maybe the first iteration, and if you see any changes are irrelevant, please tell me what to change. But i really appreciate testing of this PR on you machine to understand if it's ready to go 🚀 

---

However I read and completed all the steps in `README.md` file and I did manage to run it locally. Seems that it works as expected.

### CODE REVIEW

**Comment by jordharr** [comment]
Thanks for the contribution - i'll take a look and review during next week, due to being at NodeConf - perhaps @edeleastar can take a look in the meantime.

**Comment by edeleastar** [comment]
This is great - thanks @zenby. Looking forward to reviewing this today. Thanks again...

**Comment by edeleastar** [comment]
Hi @zenby -

When i inserted the keys (we have updated the readme to give instructions on this) - and rebuilt your branch - there was some issue which caused a course to fail to load. I could not quite see the issue.

However! - I replicated the eslint settings you committed in a new branch, and brought over your changes one by one. I made a small number of alternatives choices from yours. The result was success!

All on this branch here - https://github.com/tutors-sdk/tutors/tree/eslint-for-reader

Thanks again for this work - it was a great help. I wonder if we can see what is the differences between your PR and the one above?

**Comment by jordharr** [comment]
I have merged your branch @edeleastar - would you like to test and checkout PR to make any changes?

**Comment by zenby** [comment]
> Hi @zenby -
> 
> When i inserted the keys (we have updated the readme to give instructions on this) - and rebuilt your branch - there was some issue which caused a course to fail to load. I could not quite see the issue.
> 
> However! - I replicated the eslint settings you committed in a new branch, and brought over your changes one by one. I made a small number of alternatives choices from yours. The result was success!
> 
> All on this branch here - https://github.com/tutors-sdk/tutors/tree/eslint-for-reader
> 
> Thanks again for this work - it was a great help. I wonder if we can see what is the differences between your PR and the one above? Perhaps we can merge and accept your PR - but we might actually deploy my branch (if that makes sense)

Hi!
Thank you for the review. As I see the were couple of errors that I probably missed. 
The crucial differences between your and my branches we can probably see here https://github.com/zenby/tutors/compare/eslint-for-reader...zenby:tutors:feature/eslint-config-tutors-course-reader?expand=1

What are the further steps required from my side?

**Comment by jordharr** [comment]
> > Hi @zenby -
> > When i inserted the keys (we have updated the readme to give instructions on this) - and rebuilt your branch - there was some issue which caused a course to fail to load. I could not quite see the issue.
> > However! - I replicated the eslint settings you committed in a new branch, and brought over your changes one by one. I made a small number of alternatives choices from yours. The result was success!
> > All on this branch here - https://github.com/tutors-sdk/tutors/tree/eslint-for-reader
> > Thanks again for this work - it was a great help. I wonder if we can see what is the differences between your PR and the one above? Perhaps we can merge and accept your PR - but we might actually deploy my branch (if that makes sense)
> 
> Hi! Thank you for the review. As I see the were couple of errors that I probably missed. The crucial differences between your and my branches we can probably see here https://github.com/zenby/tutors/compare/eslint-for-reader...zenby:tutors:feature/eslint-config-tutors-course-reader?expand=1
> 
> What are the further steps required from my side?

Hey

I have merged the differences into this PR so we will take this from here - thank you for your contribution, it is really appreciated!

**Comment by zenby** [comment]
> > > Hi @zenby -
> > > When i inserted the keys (we have updated the readme to give instructions on this) - and rebuilt your branch - there was some issue which caused a course to fail to load. I could not quite see the issue.
> > > However! - I replicated the eslint settings you committed in a new branch, and brought over your changes one by one. I made a small number of alternatives choices from yours. The result was success!
> > > All on this branch here - https://github.com/tutors-sdk/tutors/tree/eslint-for-reader
> > > Thanks again for this work - it was a great help. I wonder if we can see what is the differences between your PR and the one above? Perhaps we can merge and accept your PR - but we might actually deploy my branch (if that makes sense)
> > 
> > 
> > Hi! Thank you for the review. As I see the were couple of errors that I probably missed. The crucial differences between your and my branches we can probably see here https://github.com/zenby/tutors/compare/eslint-for-reader...zenby:tutors:feature/eslint-config-tutors-course-reader?expand=1
> > What are the further steps required from my side?
> 
> Hey
> 
> I have merged the differences into this PR so we will take this from here - thank you for your contribution, it is really appreciated!

Thanks Jordan.

Do you see any similar issues to continue to work on in scope of current repository? I'm glad to help you here.

**Comment by jordharr** [comment]
> > > > Hi @zenby -
> > > > When i inserted the keys (we have updated the readme to give instructions on this) - and rebuilt your branch - there was some issue which caused a course to fail to load. I could not quite see the issue.
> > > > However! - I replicated the eslint settings you committed in a new branch, and brought over your changes one by one. I made a small number of alternatives choices from yours. The result was success!
> > > > All on this branch here - https://github.com/tutors-sdk/tutors/tree/eslint-for-reader
> > > > Thanks again for this work - it was a great help. I wonder if we can see what is the differences between your PR and the one above? Perhaps we can merge and accept your PR - but we might actually deploy my branch (if that makes sense)
> > > 
> > > 
> > > Hi! Thank you for the review. As I see the were couple of errors that I probably missed. The crucial differences between your and my branches we can probably see here https://github.com/zenby/tutors/compare/eslint-for-reader...zenby:tutors:feature/eslint-config-tutors-course-reader?expand=1
> > > What are the further steps required from my side?
> > 
> > 
> > Hey
> > I have merged the differences into this PR so we will take this from here - thank you for your contribution, it is really appreciated!
> 
> Thanks Jordan.
> 
> Do you see any similar issues to continue to work on in scope of current repository? I'm glad to help you here.

Hey,

I will be creating more issues like this on Thursday when I am back home from the conference :) Thanks

**Comment by edeleastar** [comment]
> > Do you see any similar issues to continue to work on in scope of current repository? I'm glad to help you here.
> 
Hi @zenby - yes, would certainly like more eslint related updates at least. Jordan an I will review on Thursday and populate a few issues. This time we will make sure the instructions include appropriate tests to ensure you are working on a live setup.

Thanks again

**Pull request merged**
